DROP TABLE IF EXISTS `config`;
CREATE TABLE `config` (
  `key` VARCHAR(255) PRIMARY KEY NOT NULL,
  `value` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` VARCHAR(255) PRIMARY KEY NOT NULL,
  `nickname` VARCHAR(120) NOT NULL,
  `created_at` DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

DROP TABLE IF EXISTS `web_pages`;
CREATE TABLE `web_pages` (
  `id` VARCHAR(255) PRIMARY KEY NOT NULL,
  `url` VARCHAR(2048) NOT NULL,
  `created_at` DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

DROP TABLE IF EXISTS `comments`;
CREATE TABLE `comments` (
  `id` VARCHAR(255) PRIMARY KEY NOT NULL,
  `web_page_id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  `body` VARCHAR(140) NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  UNIQUE KEY (`web_page_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;

DROP TABLE IF EXISTS `stars`;
CREATE TABLE `stars` (
  `id` VARCHAR(255) PRIMARY KEY NOT NULL,
  `comment_id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;
