#!/bin/bash

set -e

# nginx のログを削除
echo ":: CLEAR LOGS       ====>"
sudo truncate -s 0 -c /var/log/nginx/access.log

# 各種サービスの再起動
echo
echo ":: RESTART SERVICES ====>"
sudo systemctl restart mysql
sudo systemctl restart web-ruby
sudo systemctl restart nginx

sleep 5

# ベンチマークの実行
echo
echo ":: BENCHMARK        ====>"
/home/isucon/.x /home/isucon/bin/benchmarker

# alp で解析
echo
echo ":: ACCESS LOG       ====>"
sudo cat /var/log/nginx/access.log | alp ltsv -m "/api/schedules/[0-9a-zA-Z]+" --sort avg -r
